import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Header from "./header";

import { createServerComponentClient } from "@supabase/auth-helpers-nextjs";
import { cookies } from "next/headers";

export const dynamic = "force-dynamic";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Ejercicios",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const superbase = createServerComponentClient({ cookies });

  const {
    data: { session },
  } = await superbase.auth.getSession();

  return (
    <html lang="es">
      <body className={inter.className}>
        <Header session={session} />
        <main className="flex h-[calc(100vh-5rem)] flex-col items-center justify-between p-8 w-screen">
          {children}
        </main>
      </body>
    </html>
  );
}
